"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
from decouple import config
from corsheaders.defaults import default_headers
from dotenv import load_dotenv
import dj_database_url


# Load environment variables from .env (if present)
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/


# SECURITY
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", config("DJANGO_SECRET_KEY", default="unsafe-secret"))
DEBUG = os.getenv("DEBUG", "False") == "True"
ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "*").split(",")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Third party package
    "rest_framework",
    "corsheaders",
    "cloudinary",
    "cloudinary_storage",

    # Custom
    "core",
    "users",
    "wallet",
    "transactions",
    "plans",
    "support",
    "notifications",
    "landing",
    "admin_panel",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Authentication backends
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "users.backends.EmailBackend",
]

# Use custom user model
AUTH_USER_MODEL = "users.CustomUser"

# Rest Framework Configuration
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "users.authentication.CookieJWTAuthentication",  # read JWT from cookie
    )
}


# Simple JWT Authentication Config
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "UPDATE_LAST_LOGIN": True,
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_COOKIE": "access_token",
    "AUTH_COOKIE_REFRESH": "refresh_token",
    "AUTH_COOKIE_HTTP_ONLY": True,
    "AUTH_COOKIE_SECURE": True,
    "AUTH_COOKIE_SAMESITE": "None",
    "AUTH_COOKIE_DOMAIN": os.getenv("COOKIE_DOMAIN", "ever-learn-backend.onrender.com"),
    "AUTH_COOKIE_REFRESH_DOMAIN": os.getenv("COOKIE_DOMAIN", "ever-learn-backend.onrender.com"),
}


# Default cookie cross-domain settings (override in DEBUG below)
# SESSION_COOKIE_SAMESITE = "None"
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SAMESITE = "None"
# CSRF_COOKIE_SECURE = True
CSRF_COOKIE_HTTPONLY = False
COOKIE_DOMAIN = os.getenv("COOKIE_DOMAIN", None)
CSRF_COOKIE_DOMAIN = COOKIE_DOMAIN
SESSION_COOKIE_DOMAIN = COOKIE_DOMAIN


# Admin / Django sessions (safe defaults)
SESSION_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SECURE = not DEBUG


# Proxy + SSL header (Render sets X-Forwarded-Proto)
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_SSL_REDIRECT = False


# Login / logout redirects
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"


# Security headers
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True


# CSRF & CORS trusted origins
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:3001",
    "http://127.0.0.1:3000",
    "https://ever-learn.vercel.app",
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:3001",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:3001",
    "https://ever-learn.vercel.app",
]


CORS_ALLOW_HEADERS = list(default_headers)
CORS_ALLOW_CREDENTIALS = True


# Static & media
STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")


# Cloudinary media storage
MEDIA_URL = "/media/"
DEFAULT_FILE_STORAGE = "cloudinary_storage.storage.MediaCloudinaryStorage"

# MEDIA_ROOT = os.path.join(BASE_DIR, "media")


CLOUDINARY_STORAGE = {
    "CLOUD_NAME": config("CLOUDINARY_CLOUD_NAME"),
    "API_KEY": config("CLOUDINARY_API_KEY"),
    "API_SECRET": config("CLOUDINARY_API_SECRET"),
}


# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# # Resend requires a domain
# RESEND_API_KEY = config("RESEND_API_KEY", default=None)
# EMAIL_FROM = config("EMAIL_FROM", default="simmyifeanyi@gmail.com")


# ===========================
# Gmail Email Configuration
# ===========================

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True

EMAIL_PORT = 465
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True

EMAIL_HOST_USER = config("EMAIL_HOST_USER")  # your Gmail
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")  # app password
DEFAULT_FROM_EMAIL = "EverLearn (No Reply) <simmyifeanyi@gmail.com>"


# Celery configuration
# CELERY_BROKER_URL = 'redis://localhost:6379/0'
# CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_BROKER_URL = os.getenv("REDIS_URL", "redis://default:password@redis-server:6379/0")
CELERY_RESULT_BACKEND = CELERY_BROKER_URL
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'


# Environment specific overrides
if DEBUG:
    SECURE_SSL_REDIRECT = False
    SIMPLE_JWT["AUTH_COOKIE"] = "access_token"
    SIMPLE_JWT["AUTH_COOKIE_REFRESH"] = "refresh_token"
    SIMPLE_JWT["AUTH_COOKIE_HTTP_ONLY"] = True

    SIMPLE_JWT["AUTH_COOKIE_SECURE"] = False
    SIMPLE_JWT["AUTH_COOKIE_SAMESITE"] = "Lax"
    SIMPLE_JWT["AUTH_COOKIE_DOMAIN"] = None 
    SIMPLE_JWT["AUTH_COOKIE_REFRESH_DOMAIN"] = None

    CSRF_COOKIE_SECURE = False
    CSRF_COOKIE_SAMESITE = "Lax"
    COOKIE_DOMAIN = None
    CSRF_COOKIE_DOMAIN = None

    SESSION_COOKIE_SECURE = False
    SESSION_COOKIE_SAMESITE = "Lax"
    SESSION_COOKIE_DOMAIN = None

    # Use SQLite database in development
    DATABASES = {
        "default": {"ENGINE": "django.db.backends.sqlite3", "NAME": BASE_DIR / "db.sqlite3"}
    }

    # # Use console email backend in development (won't send to email)
    # EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
else:
    DATABASES = {
        "default": dj_database_url.parse(os.getenv("DATABASE_URL"), conn_max_age=600, ssl_require=True)
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
